language: ruby
cache: bundler
dist: trusty

# Early warning system to catch if Rubygems breaks something
before_install:
  - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
  - gem --version
    # travis may preinstall a bundler gem which is later than the one which we pin, which may totally hose us, so we preemtively
    # uninstall anything they may have installed here.  if they haven't installed anything then we have to ignore the failure
    # to uninstall the default bundler that ships embedded in ruby itself.
  - rvm @global do gem uninstall bundler -a -x || true
  - gem install bundler -v $(grep :bundler omnibus_overrides.rb | cut -d'"' -f2)
  - bundle --version
  - rm -f .bundle/config

before_script:
 # force all .rspec tests into progress display to reduce line count
 - echo --color > .rspec
 - echo -fp >> .rspec
 # necessary for sudo: true tests, ingore failures on tests invoked with sudo: false
 - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers

# do not run expensive spec tests on PRs, only on branches
branches:
  only:
  - master
  - chef-13
  - chef-12

env:
  global:
    - FORCE_FFI_YAJL=ext

matrix:
  include:
  - env:
      UNIT_SPECS_24: 1
    rvm: 2.4.4
    sudo: true
    script:
      - sudo -E $(which bundle) exec rake spec:unit;
      - sudo -E $(which bundle) exec rake component_specs
    bundler_args: --without ci docgen guard integration maintenance omnibus_package --frozen
  - env:
      UNIT_SPECS_25: 1
    rvm: 2.5.1
    sudo: true
    script:
      - sudo -E $(which bundle) exec rake spec:unit;
      - sudo -E $(which bundle) exec rake component_specs
    bundler_args: --without ci docgen guard integration maintenance omnibus_package --frozen

notifications:
  on_change: true
  on_failure: true
  on_success: change
  on_pull_requests: false
